# .confg/hypr/hyprland.conf

# MONITORS

# monitor = ,preferred,auto,1
monitor = eDP-1,disable
monitor = HDMI-A-1,preferred,auto,1

# VARIABLES

$mod = SUPER

$terminal = kitty
$menu = rofi -show drun
$fileManager = thunar
$browser = brave

# AUTOSTART

exec-once = waybar
exec-once = dunst
exec-once = nm-applet
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = awww-daemon
exec-once = sleep 1 && awww img /home/rp34/Pictures/Wallpapers/w3.png

# ENVIRONMENT

env = XCURSOR_SIZE,18
env = QT_QPA_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1

# INPUT

input {
    kb_layout = us

    follow_mouse = 1

    touchpad {
        natural_scroll = false
        tap-to-click = true
    }

    sensitivity = 0.5
}

# GENERAL

general {
    gaps_in = 3
    gaps_out = 5

    border_size = 0

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

# DECORATION

decoration {
    rounding = 8

    blur {
        enabled = true
        size = 5
        passes = 2
        vibrancy = 0.2
    }

    shadow {
        enabled = true
        range = 12
        render_power = 3
    }
}

# ANIMATIONS

animations {
    enabled = yes

    bezier = easeOut,0.05,0.9,0.1,1.0

    animation = windows,1,10,easeOut
    animation = windowsOut,1,10,easeOut
    animation = border,1,15,default
    animation = fade,1,10,default
    animation = workspaces,1,10,default
}

# LAYOUT

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

# KEYBINDS
source = ~/.config/hypr/keybinds.conf

# RULES
source = ~/.config/hypr/rules.conf

# MISC

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

