# KEYBINDS

bind = $mod, T, exec, $terminal
bind = $mod, D, exec, $menu
bind = $mod, E, exec, $fileManager
bind = $mod, B, exec, $browser

bind = $mod, Q, killactive,
bind = SUPER, Tab, exec, hyprlock
bind = $mod, Escape, exec, wlogout -b 1 -c 20 -r 20 -L 1700 -R 1700 -T 325 -B 325
bind = $mod, W, exec, quickshell -c hyprquickpaper

bind = $mod, F, fullscreen
bind = $mod, Space, exec, hyprctl dispatch togglefloating && hyprctl dispatch resizeactive exact 70% 70% && hyprctl dispatch centerwindow

# Toggle waybar
bind = $mod SHIFT, W, exec, sh -c 'pgrep -x waybar >/dev/null && pkill waybar || nohup waybar >/dev/null 2>&1 &'

# Screenshots
bind = $mod, Delete, exec, grim ~/Pictures/$(date +%s).png
bind = , Delete, exec, grim -g "$(slurp)" ~/Pictures/$(date +%s).png

# Clipboard
bind = $mod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

# Keyboard Layout
bind = $mod, Z, exec, hyprctl switchxkblayout current next

# Exit session
bind = $mod SHIFT, E, exit,

# Focus
bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

# Move windows
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, r

# Resize windows
binde = $mod CTRL, H, resizeactive, -40 0
binde = $mod CTRL, L, resizeactive, 40 0
binde = $mod CTRL, K, resizeactive, 0 -40
binde = $mod CTRL, J, resizeactive, 0 40

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Media keys
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
