# WINDOW RULES

# Layer rules
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.15, match:namespace rofi

windowrule {
    name = opacity
    match:class = ^(kitty|xed|thunar|brave-browser|discord|codium|GeForceNOW|obsidian|Spotify|org.pulseaudio.pavucontrol|com.github.johnfactotum.Foliate)$

    opacity = 0.6 override 0.6 override 1.0 override
}

windowrule {
    name = float
    match:class = ^(pavucontrol)$
}

windowrule {
    name = float
    match:class = ^(nm-connection-editor)$
}

windowrule {
    name = float
    match:class = ^(blueman-manager)$
}

windowrule {
    name = float
    match:title = ^(Open File)$
}

windowrule {
    name = float
    match:title = ^(Save File)$
}
