# WINDOW RULES

# Layer rules
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.15, match:namespace rofi

windowrule {
    name = opacity
    match:class = ^(kitty|xed|Thunar|brave-browser|discord|codium|GeForceNOW|obsidian|Spotify|com.github.johnfactotum.Foliate|)$
    opacity = 0.7 0.7
}

windowrule {
    name = float
    match:class = ^(pavucontrol)$
}

windowrule {
    name = float
    match:class = ^(nm-connection-editor)$
}

windowrule {
    name = float
    match:class = ^(blueman-manager)$
}

windowrule {
    name = float
    match:title = ^(Open File)$
}

windowrule {
    name = float
    match:title = ^(Save File)$
}
